add mock location and ip to wolfram
Run1e/AceBot pull request #35
Opened 2021-04-23 00:51 UTC by onerandomusername

As of now, location based queries to wolfram alpha error because the ip address provided is empty.
![image](https://user-images.githubusercontent.com/71233171/115802192-6f2f3800-a3ac-11eb-8df4-b062bed2d7fd.png)

This solves that issue by providing a mock ip address of cloudfare's dns servers, 1.1.1.1, and by giving a latitude and longitude of 0 degrees.
![image](https://user-images.githubusercontent.com/71233171/115802183-676f9380-a3ac-11eb-9aa0-a8ec81df7ca1.png)

2021-04-23 13:40 UTC, Micha-ohne-el commented
I don't think this fix is a good idea. You can already specify a location (`.w next full moon in New York`) and specifying no location is pretty meaningless anyway. Defaulting to some random location is unintuitive and misleading, imo.
I think it should get an improved error message. Catch the exception, see if the error was no IP Address / location specified, then show a reasonable error message.

2021-04-30 05:19 UTC, onerandomusername commented
> I don't think this fix is a good idea. You can already specify a location (`.w next full moon in New York`) and specifying no location is pretty meaningless anyway. Defaulting to some random location is unintuitive and misleading, imo.
I think it should get an improved error message. Catch the exception, see if the error was no IP Address / location specified, then show a reasonable error message. 

The reason to provide the mock parameters is to let every search work, even if the results aren't fully accurate. Upon further thought, what about a combination of both? Providing 0.0 for lat and long is taken as a default on most map apps when they don't have access to your location.

I do agree that its possible for the api to have no pods in the result, which does mean that error should be gracefully handled.

2021-04-30 15:34 UTC, Micha-ohne-el commented
I don't think each search should work, that's the thing. Asking “when is the next full moon?” is like asking “how far is it to the next airport?”, there is no useful answer here if WolframAlpha doesn't know your location. Yes, you can estimate a location, and in the case of moon phases that may be accurate enough, but for quite a lot of things, this is pretty meaningless.

The better error message, however, is definitely a good idea probably for even more cases than just this.

2021-04-30 15:38 UTC, onerandomusername commented
I've added a check so in the event that there aren't any pods, the current wolfram error message is shown.
I've also reverted the location override.
![image](https://user-images.githubusercontent.com/71233171/116702660-5a980480-a997-11eb-9e08-586ab78a5847.png)

2021-05-04 01:33 UTC, Run1e requested changes

2021-05-04 01:33 UTC, Run1e commented on cogs/fun.py
> +			success = bool(res['success'] and res['numpods'])
Wrapping in bool(...) is not necessary since `x and y` returns a boolean value already

2021-05-04 01:33 UTC, Run1e commented on cogs/fun.py
> +				if len(e.fields) == 0 and res['numpods'] == 0:
`len(e.fields) == 0` can be replaced with `e.fields`

2021-05-04 01:33 UTC, Run1e commented on cogs/fun.py
> +									value=(
Funky indents

2021-05-06 05:22 UTC, merged