update the '.ask' reply when channels are claimed
Run1e/AceBot pull request #40
Opened 2021-04-29 23:02 UTC by onerandomusername

Closes #38 

When a help channel is claimed, all `.ask` replies between the last claimed channel are edited to link to the `GET_HELP_CHAN_ID` channel. 

![image](https://user-images.githubusercontent.com/71233171/116628526-516a5180-a91d-11eb-94d3-372e87cc5427.png) 

This limits the confusion that occurs when it still references now claimed channels.

2021-05-04 01:42 UTC, Run1e requested changes
The caching is a bit wonky but can be fixed easily by holding the last few .ask messages and updating those, and pushing the oldest message out when its full. A simple list can do this, or you can use the deque class from collections.

2021-05-04 01:42 UTC, Run1e commented on cogs/ahk/help.py
> +	"If you're looking for scripting help you should ask in an open help channel.\n\n"
Use single quotes

2021-05-04 01:42 UTC, Run1e commented on cogs/ahk/help.py
> +	"If you're looking for scripting help you should ask in an open help channel.\n\n"
Use single quotes

2021-05-04 01:42 UTC, Run1e commented on cogs/ahk/help.py
> +		#clear the list since all of them have been resolved now.
What if another channel is claimed right after? I think a solution where the last three .ask messages are held in the self.ask_messages cache will be the best solution. Simply clearing the list after updating the messages once can lead to the messages being outdated and wrong very quickly.

2022-12-25 20:18 UTC, onerandomusername commented
this has been superceded by the forum help system

2022-12-25 20:18 UTC, closed without merging